import type { Catalog } from './types';

const now = '2026-06-16T00:00:00.000Z';

export const seedCatalog: Catalog = {
  exercises: [
    {
      id: 'exercise-brisk-walking',
      name: '快走',
      summary: '低门槛、低冲击的有氧运动，适合作为减脂起步训练。',
      category: '有氧',
      difficulty: 'easy',
      methodSteps: ['热身 5 分钟', '保持能说话但略喘的速度快走', '结束后拉伸小腿和大腿后侧'],
      durationMinutes: 30,
      metValue: 4.3,
      caloriesReference: 180,
      persistenceTips: ['固定饭后 1 小时进行', '先从每周 3 次开始'],
      contraindications: ['急性关节疼痛或胸闷不适时暂停运动并咨询医生'],
      tags: ['低冲击', '入门'],
      status: 'enabled',
      sortOrder: 10,
      sourceUrls: ['https://www.cdc.gov/physical-activity-basics/index.html'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'exercise-cycling',
      name: '骑行',
      summary: '对膝关节压力较小，可持续提升心肺耐力。',
      category: '有氧',
      difficulty: 'medium',
      methodSteps: ['调整车座高度', '以中等阻力骑行', '保持稳定踏频'],
      durationMinutes: 40,
      metValue: 6.8,
      caloriesReference: 320,
      persistenceTips: ['选择通勤或固定骑行台场景', '用时长目标替代速度攀比'],
      contraindications: ['腰背疼痛明显者先调整姿势或降低强度'],
      tags: ['心肺', '低冲击'],
      status: 'enabled',
      sortOrder: 20,
      sourceUrls: ['https://www.cdc.gov/physical-activity-basics/index.html'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'exercise-strength-circuit',
      name: '自重循环训练',
      summary: '结合深蹲、俯卧撑、平板支撑等动作，帮助保留肌肉量。',
      category: '力量',
      difficulty: 'medium',
      methodSteps: ['选择 4 个动作', '每个动作 30 秒', '休息 30 秒后进入下一轮'],
      durationMinutes: 25,
      metValue: 5,
      caloriesReference: 220,
      persistenceTips: ['记录完成轮数', '每两周小幅增加一组'],
      contraindications: ['动作疼痛时停止，优先学习正确姿势'],
      tags: ['力量', '居家'],
      status: 'enabled',
      sortOrder: 30,
      sourceUrls: ['https://www.cdc.gov/physical-activity-basics/index.html'],
      createdAt: now,
      updatedAt: now,
    },
  ],
  foods: [
    {
      id: 'food-chicken-breast',
      name: '鸡胸肉',
      summary: '高蛋白、低脂肪，常用于减脂期主菜。',
      category: '蛋白质',
      caloriesPer100g: 165,
      protein: 31,
      fat: 3.6,
      carbs: 0,
      servingSuggestion: '建议蒸、煮、煎烤少油烹饪。',
      tags: ['高蛋白'],
      status: 'enabled',
      sortOrder: 10,
      sourceUrls: ['https://fdc.nal.usda.gov/'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'food-broccoli',
      name: '西兰花',
      summary: '热量较低，膳食纤维丰富，适合搭配主食和蛋白质。',
      category: '蔬菜',
      caloriesPer100g: 34,
      protein: 2.8,
      fat: 0.4,
      carbs: 6.6,
      servingSuggestion: '焯水后少油快炒或凉拌。',
      tags: ['低热量', '高纤维'],
      status: 'enabled',
      sortOrder: 20,
      sourceUrls: ['https://fdc.nal.usda.gov/'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'food-oats',
      name: '燕麦',
      summary: '饱腹感较强，适合作为早餐主食来源。',
      category: '主食',
      caloriesPer100g: 389,
      protein: 16.9,
      fat: 6.9,
      carbs: 66.3,
      servingSuggestion: '控制份量，搭配牛奶、酸奶或水果。',
      tags: ['主食', '饱腹'],
      status: 'enabled',
      sortOrder: 30,
      sourceUrls: ['https://fdc.nal.usda.gov/'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'food-egg',
      name: '鸡蛋',
      summary: '优质蛋白和脂溶性营养素来源。',
      category: '蛋白质',
      caloriesPer100g: 143,
      protein: 12.6,
      fat: 9.5,
      carbs: 0.7,
      servingSuggestion: '水煮或蒸蛋更利于控制油脂摄入。',
      tags: ['高蛋白'],
      status: 'enabled',
      sortOrder: 40,
      sourceUrls: ['https://fdc.nal.usda.gov/'],
      createdAt: now,
      updatedAt: now,
    },
  ],
  recipes: [
    {
      id: 'recipe-chicken-salad',
      name: '鸡胸肉蔬菜沙拉',
      summary: '高蛋白低油脂，适合作为午餐或晚餐。',
      mealType: '午餐',
      ingredients: ['鸡胸肉', '生菜', '番茄', '玉米粒', '无糖酸奶'],
      steps: ['鸡胸肉煮熟撕条', '蔬菜洗净切块', '用无糖酸奶和黑胡椒调味'],
      caloriesPerServing: 360,
      macros: { protein: 35, fat: 8, carbs: 32 },
      suitableFor: ['normal', 'overweight', 'obese'],
      tags: ['高蛋白', '低油'],
      status: 'enabled',
      sortOrder: 10,
      sourceUrls: ['https://www.myplate.gov/'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'recipe-oats-yogurt',
      name: '燕麦酸奶杯',
      summary: '方便准备的早餐，注意控制燕麦和坚果份量。',
      mealType: '早餐',
      ingredients: ['燕麦', '无糖酸奶', '蓝莓', '奇亚籽'],
      steps: ['燕麦提前浸泡', '加入酸奶和水果', '冷藏后食用'],
      caloriesPerServing: 310,
      macros: { protein: 18, fat: 9, carbs: 42 },
      suitableFor: ['normal', 'overweight'],
      tags: ['早餐', '饱腹'],
      status: 'enabled',
      sortOrder: 20,
      sourceUrls: ['https://www.myplate.gov/'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'recipe-broccoli-egg',
      name: '西兰花鸡蛋碗',
      summary: '蔬菜和蛋白质组合，适合轻食晚餐。',
      mealType: '晚餐',
      ingredients: ['西兰花', '鸡蛋', '糙米饭', '胡萝卜'],
      steps: ['西兰花焯水', '鸡蛋水煮切块', '搭配少量糙米饭'],
      caloriesPerServing: 420,
      macros: { protein: 24, fat: 12, carbs: 54 },
      suitableFor: ['overweight', 'obese'],
      tags: ['轻食', '高纤维'],
      status: 'enabled',
      sortOrder: 30,
      sourceUrls: ['https://www.myplate.gov/'],
      createdAt: now,
      updatedAt: now,
    },
  ],
  medicines: [
    {
      id: 'medicine-orlistat',
      name: '奥利司他',
      summary: '脂肪酶抑制剂，减少部分膳食脂肪吸收。',
      type: '药物',
      mechanism: '通过抑制胃肠道脂肪酶，减少膳食脂肪分解与吸收。',
      suitableDescription: '通常用于需要医学减重管理的人群，是否适合需由医生判断。',
      usageNote: '仅做科普介绍，具体使用方式应遵医嘱或按药品说明书。',
      sideEffects: ['油性便', '胃肠不适', '脂溶性维生素吸收受影响'],
      contraindications: ['慢性吸收不良综合征', '胆汁淤积', '妊娠或备孕需咨询医生'],
      medicalWarning: '不应自行长期使用减重药物，出现明显不适应及时就医。',
      tags: ['处方/非处方因地区而异', '脂肪吸收'],
      status: 'enabled',
      sortOrder: 10,
      sourceUrls: ['https://www.accessdata.fda.gov/'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'medicine-l-carnitine',
      name: '左旋肉碱',
      summary: '常见膳食补充剂，减脂效果证据有限。',
      type: '补剂',
      mechanism: '参与脂肪酸转运代谢，但补充并不等于直接燃脂。',
      suitableDescription: '一般作为营养补充剂了解，不建议替代饮食和运动管理。',
      usageNote: '如正在用药、孕期或有基础疾病，使用补剂前应咨询医生。',
      sideEffects: ['胃肠不适', '体味改变', '可能与部分药物相互影响'],
      contraindications: ['癫痫史或特殊代谢疾病人群需谨慎'],
      medicalWarning: '补剂不是减肥药，不能承诺体重下降效果。',
      tags: ['补剂', '证据有限'],
      status: 'enabled',
      sortOrder: 20,
      sourceUrls: ['https://ods.od.nih.gov/factsheets/Carnitine-HealthProfessional/'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'medicine-white-kidney-bean',
      name: '白芸豆',
      summary: '常见碳水阻断概念补剂，效果和个体差异较大。',
      type: '补剂',
      mechanism: '部分产品宣称通过影响淀粉酶活性减少碳水分解。',
      suitableDescription: '可作为补剂知识了解，不建议依赖其抵消高热量饮食。',
      usageNote: '关注产品成分、剂量和合规来源，特殊人群先咨询医生。',
      sideEffects: ['腹胀', '排气增加', '胃肠不适'],
      contraindications: ['消化系统疾病或孕期人群需谨慎'],
      medicalWarning: '不要用补剂替代热量控制和均衡饮食。',
      tags: ['补剂', '碳水管理'],
      status: 'enabled',
      sortOrder: 30,
      sourceUrls: ['https://www.nccih.nih.gov/'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'medicine-tirzepatide',
      name: '替尔泊肽',
      summary: 'GLP-1/GIP 受体相关药物，需严格遵医嘱使用。',
      type: '药物',
      mechanism: '通过影响食欲、胃排空和血糖代谢等途径参与体重管理。',
      suitableDescription: '是否适合用于减重需结合 BMI、合并症和医生评估。',
      usageNote: '仅做科普介绍，不能自行购买或调整剂量。',
      sideEffects: ['恶心', '呕吐', '腹泻', '便秘', '低血糖风险因合并用药而异'],
      contraindications: ['特定甲状腺肿瘤病史', '多发性内分泌腺瘤综合征 2 型风险人群'],
      medicalWarning: '此类药物必须由医生评估适应证、禁忌证和随访计划。',
      tags: ['处方药', '需医生评估'],
      status: 'enabled',
      sortOrder: 40,
      sourceUrls: ['https://www.fda.gov/'],
      createdAt: now,
      updatedAt: now,
    },
  ],
};
