name = "fitness-api"
main = "src/index.ts"
compatibility_date = "2026-06-16"
routes = [
  { pattern = "fitness-api.cup.kdns.fr", custom_domain = true }
]

[vars]
CORS_ORIGIN = "http://localhost:5173,https://fitness.cup.kdns.fr"

[[kv_namespaces]]
binding = "FITNESS_KV"
id = "88988ce47b434b25bdef2c06d3b99531"
preview_id = "9dce1f45abf04696b2abbdca6f8c4274"
